name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.0.1
        with:
          tags: scwiki/discord-bot:latest
